defaults:
  run:
    shell: "bash"

name: "Create Release PR"

on:
  workflow_dispatch:
    inputs:
      args:
        description: "Badabump arguments (pass `--pre` to start or keep pre-release cycle)"
        required: false
        default: ""

env:
  POETRY_VERSION: "1.1.12"
  PYTHON_VERSION: "3.10.1"
  PYTHONUNBUFFERED: "1"

jobs:
  create_release_pr:
    if: "${{ github.actor == 'playpauseandstop' }}"
    name: "Create release PR"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.4.0"
        with:
          ref: "master"

      - name: "Fetch git tags"
        run: |
          set -euo pipefail

          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || :
          git fetch --prune --unshallow

      - name: "Install Python"
        uses: "actions/setup-python@v2.3.1"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: "Install poetry"
        run: "python3 -m pip install poetry==${{ env.POETRY_VERSION }}"

      - name: "Cache venv"
        uses: "actions/cache@v3.0.2"
        with:
          path: ".venv"
          key: "venv-${{ env.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}"

      - name: "Install badabump"
        run: "poetry install --no-dev"

      - id: "badabump"
        name: "Run badabump"
        run: "poetry run python3 -m badabump --ci ${{ github.event.inputs.args }}"

      - id: "token"
        uses: "tibdex/github-app-token@v1.5"
        with:
          app_id: "${{ secrets.BADABUMP_APP_ID }}"
          private_key: "${{ secrets.BADABUMP_APP_PRIVATE_KEY }}"

      - name: "Create pull request with changed files"
        uses: "peter-evans/create-pull-request@v3.12.1"
        with:
          token: "${{ steps.token.outputs.token }}"
          commit-message: |
            ${{ steps.badabump.outputs.pr_title }}

            ${{ steps.badabump.outputs.changelog }}
          branch: "${{ steps.badabump.outputs.pr_branch }}"
          delete-branch: true
          title: "${{ steps.badabump.outputs.pr_title }}"
          body: "${{ steps.badabump.outputs.changelog }}"
          labels: "chore"
          reviewers: "playpauseandstop"
          assignees: "playpauseandstop"
