defaults:
  run:
    shell: "bash"

name: "Auto Create Release Tag"

on:
  pull_request:
    types: ["closed"]

env:
  PYTHONUNBUFFERED: "1"

jobs:
  create_release_tag:
    if: "${{ startsWith(github.head_ref, 'chore/release-') && github.event.pull_request.merged == true }}"
    name: "Auto Create Release Tag"

    runs-on: "ubuntu-24.04"

    steps:
      - id: "token"
        uses: "tibdex/github-app-token@v2.1.0"
        with:
          app_id: "${{ secrets.BADABUMP_APP_ID }}"
          private_key: "${{ secrets.BADABUMP_APP_PRIVATE_KEY }}"

      - uses: "actions/checkout@v7.0.0"
        with:
          token: "${{ steps.token.outputs.token }}"
          ref: "${{ github.repository.default_branch }}"

      - uses: "./.github/actions/install_python_and_poetry"
        with:
          python-version-file: ".python-version"

      - name: "Install badabump"
        run: "poetry install --only=main"

      - id: "badabump"
        name: "Run badabump"
        run: "poetry run python3 -m badabump.ci prepare_tag"

      - name: "Save tag message into the file"
        env:
          TAG_MESSAGE: "${{ steps.badabump.outputs.tag_message }}"
        run: printf '%s' "${TAG_MESSAGE}" > ./tag_message.txt

      - name: "Create release tag from latest commit"
        run: |
          set -euo pipefail

          git config user.name badabump-bot[bot]
          git config user.email 86060+badabump-bot[bot]@users.noreply.github.com

          git tag -a ${{ steps.badabump.outputs.tag_name }} -F ./tag_message.txt
          git push --tag
